# -*- coding: utf-8 -*-
"""
for <control variable> in <range/sequence>:
    ....
    ....
    ....
else: (optional)
    ....
    ....
    ....
"""
name="Harshit and Biraag"
for x in name:
    print(x)
count=[10,30,19,2,39,12,39,93,12,41,42,21,33]
for i in count:
    if(i%2==0):
        print(i)